# Preface {.unnumbered}

# 학습 자료

코딩할 프로젝트 목록 외에 사람들이 가장 많이 묻는 다른 질문은 **어디서 코딩을 배울 수 있나요?**입니다.
이 파일은 코딩 방법을 배우고 기술을 연마하는 데 도움이 될 리소스 목록(언어/프레임워크로 태그 지정)을 컴파일하려는 저의 시도입니다. 현재 목록은 무작위이지만 곧 어떤 방식(알파벳순 또는 언어별)으로든 정리할 것입니다.

## 어떤 언어를 배워야 할까요

다음은 귀하의 필요에 가장 적합한 언어를 선택한 다음 그에 따라 진행하는 데 도움이 되도록 [r/learnprogramming](https://www.reddit.com/r/learnprogramming/wiki/faq#wiki_which_programming_language_should_i_start_with.3F)에서 수정한 표입니다.

| 배우고 싶은 것... | 배우는 것을 고려해보세요... |
|---------------------------|----------------------|
| ...iPhone 앱 만들기 | Swift 및 Objective-C |
| ...Android 앱 만들기 | Kotlin 또는 Java |
| ...웹사이트 구축 | JavaScript, CSS, HTML |
| ...Windows 데스크톱 응용 프로그램 작성 | C# |
| ...2D 또는 3D 게임 만들기 | JavaScript, C# 또는 C++ |
| ...Arduino/마이크로 컨트롤러/로봇 프로그래밍 | C |
| ...과학/수학 컴퓨팅 또는 데이터 분석 수행 | Julia, Python, R 또는 MATLAB |
| ...자동화 및 스크립팅 수행 | 많은 언어(Python, Ruby, Bash, PowerShell, AutoHotKey, ...) |
| ...동적 웹페이지 구축 | HTML, CSS, JavaScript, Ruby on Rails, PHP |
| ...데이터베이스 구축 및 관리 | SQL |

<!--
템플릿
## 리소스

설명

**무료/유료:**
**언어/프레임워크:**
-->

### MDN (Mozilla Developer Network)

[MDN](https://developer.mozilla.org/en-US/)은 웹과 관련된 모든 것에 대한 리소스입니다. CSS, HTML, 웹 표준, 프로토콜, JavaScript 및 기타 사항과 같은 언어 및 주제를 다루는 방대한 리소스입니다. 그들의 튜토리얼은 초보자가 기본을 배우기에 좋고, 참조는 숙련된 개발자가 빠른 검색이 필요할 때 좋습니다.

**무료/유료:** 무료
**언어/프레임워크:** CSS, HTML, JavaScript 및 웹과 관련된 거의 모든 것.

### CSS-Tricks

[CSS-Tricks](https://css-tricks.com/)는 CSS(및 디자인 고려 사항)에 대한 환상적인 리소스입니다. 확인할 수 있는 심층 가이드가 많이 있습니다. 배울 수 있는 좋은 장소일 뿐만 아니라 확인할 가치가 있는 뉴스레터도 있습니다. 고품질 리소스이며 프런트 엔드 개발에 시간을 할애하면 나타날 리소스입니다.

**무료/유료:** 무료
**언어/프레임워크:** CSS

### Marksheet.io

[Marksheet.io](https://marksheet.io/)는 CSS 및 HTML에 대한 기억을 새로 고칠 수 있는 간결하고 간단한 사이트입니다. 무슨 일이 일어나고 있는지 시각화하는 데 도움이 되는 좋은 그래픽 그림이 있습니다. 요점으로 바로 들어가는 헛소리 없는 리소스로 권장됩니다.

**무료/유료:** 무료
**언어/프레임워크:** HTML 및 CSS

### Interneting is Hard

[Interneting is Hard](https://www.internetingishard.com/)는 초보자가 디자인에 중점을 두고 HTML 및 CSS에 대해 배우는 것을 돕는 것을 목표로 합니다. 상세하고 실용적인 리소스입니다. 코드 작성의 중요성과 그것이 당신이 하는 일을 이해하는 데 어떻게 도움이 되는지를 강조합니다. 손을 더럽히고 일이 어떻게 작동하는지 실제로 보는 것을 좋아한다면 시작하기에 좋은 곳입니다.

**무료/유료:** 무료
**언어/프레임워크:** HTML 및 CSS

### CSS 필수 교육

[CSS 필수 교육](https://www.lynda.com/CSS-tutorials/Styling-documents-consistently/5038219/2249020-4.html)은 lynda에서 제공되는 비디오 과정으로 CSS의 기본을 가르치는 것을 목표로 합니다. 훌륭한 CSS 101 학습 리소스입니다.

**무료/유료:** 유료
**언어/프레임워크:** CSS

### The Odin Project

[The Odin Project](https://theodinproject.com/)는 웹 개발을 무료로 가르치기 위한 오픈 소스 노력입니다. GitHub 프로필에 구축하고 전시할 수 있는 훌륭한 프로젝트가 있습니다. 이 웹사이트는 웹 개발자를 위한 'the' 리소스가 되도록 의도되었으며 직업 지원 및 취업 방법에 대한 최종 과정도 제공합니다.

**무료/유료:** 무료
**언어/프레임워크:** JavaScript, Node.js, Ruby on Rails, 프런트 엔드도(HTML, CSS)

### Full Stack Open

[Full Stack Open](https://fullstackopen.com/en/)은 JavaScript를 사용한 최신 웹 앱 개발 소개 역할을 합니다. 주로 REST API 및 Node.js를 사용하여 ReactJS로 단일 페이지 응용 프로그램을 구축하는 데 중점을 둡니다. 이 과정은 헬싱키 대학교 컴퓨터 과학과의 과정과 동일하며 관련 캡스톤 프로젝트도 있습니다.

**무료/유료:** 무료
**언어/프레임워크:** ReactJS, JavaScript, TypeScript, MongoDB, Node.js, GraphQL, MERN

### App Academy

[App Academy](https://open.appacademy.io/)는 미국 최고의 코딩 부트캠프라고 자랑합니다. 상당한 양의 무료 자료(약 1500시간 분량의 자료)와 참여적인 커뮤니티가 있습니다. 초점은 사람들을 다른 회사에 배치하는 데 있습니다. 또한 가격에 따라 일을 더 쉽게 만들어주는 멘토십 트랙도 있습니다.

**무료/유료:** 무료 / 유료 (멘토십 플랜 $29.99)
**언어/프레임워크:** Ruby on Rails, MERN, JavaScript

### Solo Learn

[Solo Learn](https://www.sololearn.com/)은 다양한 언어에 대한 기본적인 이해를 돕는 짧은 과정을 제공합니다. 이 과정은 특정 언어에 대한 기억을 새로 고치거나 처음부터 배우기에 이상적입니다. 또한 그 과정에서 지식을 테스트하는 데 도움이 되는 짧은 퀴즈도 제공합니다.

**무료/유료:** 무료
**언어/프레임워크:** *많은* 언어

### Free Code Camp

[Free Code Camp](https://www.freecodecamp.org/)는 초보자도 소프트웨어 개발의 길을 제공합니다. 이 과정은 코드에서 무언가를 변경할 때 무슨 일이 일어나고 있는지 감을 잡는 데 도움이 되는 대화형 코드를 통해 진행됩니다. 또한 인터뷰 준비에 도움이 되는 코딩 인터뷰 준비 자료도 있습니다.

**무료/유료:** 무료
**언어/프레임워크:** Python, JavaScript, Node.js, MongoDB, HTML, CSS

### Python Programming

[Python Programming](https://pythonprogramming.net/)은 Python만 다룹니다. 그러나 특정 틈새 시장에 특화하기 위해 취할 수 있는 많은 경로를 제공합니다. Python의 기본부터 시작하여 게임 개발, 양자 컴퓨팅, 기계 학습 및 기타 여러 분야의 과정을 제공합니다.

**무료/유료:** 무료
**언어/프레임워크:** Python

### Devoted Learner

[Devoted Learner](https://devotedlearner.com/how-to-become-a-machine-learning-engineer/#Introduction)는 블로그와 같습니다. 기계 학습 엔지니어가 되는 방법에 대한 리소스와 팁이 포함된 블로그 게시물이 포함되어 있습니다. 초보자를 위한 좋은 리소스입니다.

**무료/유료:** 무료
**언어/프레임워크:** Python

### Python Principles

[Python Principles](https://pythonprinciples.com/)는 초보자를 위한 Python의 기본을 제공합니다. Python의 기본을 이해하고 사용하는 데 도움이 되는 많은 예제와 챌린지가 있는 잘 구축된 리소스입니다.

**무료/유료:** 무료 / 유료 (프로 $29)
**언어/프레임워크:** Python

### Learn X in Y minutes

[Learn X in Y minutes](https://learnxinyminutes.com/)는 다양한 언어에 대한 구문의 귀중한 라이브러리입니다. 언어에 대한 권장 치트 시트입니다.

**무료/유료:** 무료
**언어/프레임워크:** *많은* 언어

### Rosettacode

[Rosettacode](http://rosettacode.org/wiki/Rosetta_Code)는 프로그래밍 [chrestomathy](https://en.wikipedia.org/wiki/Chrestomathy) 사이트입니다. 언어가 어떻게 유사하고 다른지, 그리고 다른 언어가 동일한 문제에 대해 다른 접근 방식으로 이어질 수 있는지를 보여주기 위해 다양한 언어로 주어진 질문에 답하는 것을 목표로 합니다.

**무료/유료:** 무료
**언어/프레임워크:** *많은* 언어

## 참고 자료
- [CSS 마스터가 되는 데 도움이 된 5가지 리소스 - Reddit](https://www.reddit.com/r/learnprogramming/comments/in3jvg/the_5_resources_that_helped_me_become_a_css/)
- [오래 전에 알았으면 좋았을 리소스! - Reddit](https://www.reddit.com/r/learnprogramming/comments/icr9ac/resources_i_wish_i_knew_about_long_ago/)
- [r/learnprogramming FAQs](https://www.reddit.com/r/learnprogramming/wiki/faq)
